---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:latest

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c -v"

dependencies:
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core==2.16.14
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system: bindep.txt

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
  - src: files/certs/web.bk.lab.crt
    dest: certs
  - src: files/certs/web.bk.lab.key
    dest: certs

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    - ADD _build/certs/web.bk.lab.crt /certs/web.bk.lab.crt
    - ADD _build/certs/web.bk.lab.key /certs/web.bk.lab.key
    - RUN rm -f /etc/ansible/ansible.cfg

options:
  package_manager_path: /usr/bin/dnf

